apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: automateddevopspipeline
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/jumatos/DevOps-Project-AutomationCICD.git
    targetRevision: main
    path: automateddevopspipeline

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true