image:
  repository: juanmats99/devops-project-cicd
  tag: 8b514a8
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
   enable: false
serviceAccount:
   enable: false
autoscaling:
   enable: false
   
