image:
  repository: juanmats99/devops-project-cicd
  tag: 3748e22
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

httpRoute:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false