---
name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build Docker Image
        run: |
          docker build \
            -t juanmats99/devops-project-cicd:${{ env.SHORT_SHA }} \
            -t juanmats99/devops-project-cicd:latest \
            .

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Push to DockerHub
        run: |
          docker push juanmats99/devops-project-cicd:${{ env.SHORT_SHA }}
          docker push juanmats99/devops-project-cicd:latest
      - name: Configure Git Author
        run: |
         git config --local user.email "juanmats99@gmail.com"
         git config --local user.name "jumatos"
      - name: Upadte Helm Chart with new image tag
        run: | 
           sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/"  ./automateddevopspipeline/values.yaml
           git add ./automateddevopspipeline/values.yaml
           git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
           git push 

